name: Build Magnum Deb Packages
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build for Bionic
      run: ./build.sh bionic

    - name: Build for Focal
      run: ./build.sh focal

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
	GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
	with:
	  tag_name: ${{ github.ref }}
	  release_name: ${{ github.ref }}
	  draft: false
	  prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: alexellis/upload-assets@0.2.2
      env:
	GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
	with:
	  asset_paths: '["./focal/*.deb", "./bionic/*.deb"]'
	  upload_url: ${{ steps.create_release.outputs.upload_url }} 
