name: Build Magnum Deb Packages
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the images
      run: ./build.sh
